### ISSUE TITLE
Milvus Lite Server Fails to Start

### ISSUE THREAD

**Issue by romellfudi** [milvus-io/milvus-lite#64]
I have been thoroughly testing the Milvus Lite library for the past few weeks, and while I have found it to be an awesome tool, I recently encountered an issue. In particular, I attempted to run Milvus server on my Google Colab notebooks, but unfortunately, I faced an obstacle: the Milvus server failed to start. Even the Colab example in provided in your repository didn't work as expected.

![Screen Shot 2023-08-14 at 6 11 11 PM](https://github.com/milvus-io/milvus-lite/assets/1668017/722e3d8e-1d42-46a7-a519-b0fa399e0bf9)

**Comment by matrixji** [comment]
try using `debug_server ` instead of `default_server`, then could see more details on the screen of what happened.

Maybe you cloud also try default_server.cleanup() before server start

**Comment by romellfudi** [comment]
Thank you for your immediate response. I have been attempting various methods to initiate the server, but I continue to encounter the same issue, which presents as a TimeoutError.

![Screen Shot 2023-08-15 at 12 02 36 PM](https://github.com/milvus-io/milvus-lite/assets/1668017/6ad7c26d-b433-468b-8487-eabd653f6842)

Despite my efforts, including trying different versions of Milvus and grpcio, I have consistently this problem. Unfortunately, no additional information has been provided in the logs.

**Comment by yhmo** [comment]
@romellfudi 

The root cause is the previous milvus server was not stopped. 
For instance, you start a python script with debug mode and call default_server.start(), but the script was terminated for some reason. Then the milvus server is still running. And you run the script again to try defaul_server.start() again, the new server will get error because the data path is occupied by the old server.

If you type the command `"ps -e | grep milvus" `to list the process, you will see the milvus server is still running.

To avoid this error, we need to kill the old server process.
Paste these lines into a file stop.sh:
```
echo "Stopping milvus..."
PROCESS=$(ps -e | grep milvus | grep -v grep | awk '{print $1}')
if [ -z "$PROCESS" ]; then
  echo "No milvus process"
  exit 0
fi
kill -9 $PROCESS
echo "Milvus stopped"
```
And run this stop.sh in command line, it will force stop the old server. Then type "ps -e | grep milvus" again to check the old server is stopped. Now you can call default_server.start() again to start a new server.

**Comment by romellfudi** [comment]
@yhmo @matrixji 
I can run Milvus on my PC correctly, but I cannot start Milvus Lite in Google Colaboratory. Can you?
I managed to do it a month ago. I am currently writing a blog about this vectorized database; that's why I want to include a Colab notebook.

**Comment by matrixji** [comment]
https://colab.research.google.com/drive/1p_A7440mfggc2We29JV9MIhI_6rjV5-V?usp=sharing
I have reproduced it on colab, the above link could explain why it failed, I'll try to fix it and provide a fixed post version.

**Comment by matrixji** [comment]
@romellfudi pls have tried the latest version under colab. `milvus 2.2.13.post2` should fix this problem

**Comment by romellfudi** [comment]
@matrixji, thank you so much! You're rocks!

**Comment by matrixji** [comment]
> @matrixji, thank you so much! You're rocks!

Thanks a lot, looking forward to your articles. :-)
